import type { Metadata } from "next";
import "./globals.css";
import { ReactNode } from "react";
import ThemeRegistry from "@/components/ThemeRegistery";
import Sidebar from "@/components/Sidebar";
import { Grid } from "@mui/material";
import { grotesk } from "@/utils/fonts";
import { AppProviders } from "@/redux/store/provider";
import { Toaster } from "react-hot-toast";
import ToastBridge from "@/components/ToastBridge";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body >
        <AppProviders>
        <ThemeRegistry>
          <Grid container  sx={{ minHeight: "100vh" }}>
            {/* Sidebar */}
            <Grid
              size={{xs:12,sm:3,md:2}}
           
              sx={{
                bgcolor: "background.paper",
                
               
              }}
            >
              <Sidebar />
            </Grid>

            {/* Main Content */}
            <Grid size={{xs:12,sm:9,md:10}}  sx={{ fontFamily:grotesk.style }}>
              {children}
              <ToastBridge/>
              <Toaster position="top-right" toastOptions={{duration:3000}} />
              
            </Grid>
            
          </Grid>
        </ThemeRegistry>
        </AppProviders>
      </body>
    </html>
  );
}
